FROM femtopixel/google-chrome-headless AS FEMTOPIXEL

USER root
# Install deps + add Chrome Stable + purge all the things
RUN rm -rf /var/lib/apt/lists/* && \
  apt-get update && \
  apt-get remove gnupg -y && apt-get install --reinstall gnupg2 dirmngr --allow-unauthenticated -y && \
  apt-get autoclean && apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg --no-install-recommends && \
  curl -sSL https://deb.nodesource.com/setup_14.x | bash - && \
  apt-get install -y nodejs --no-install-recommends && \
  npm --global install npm && \
  npm --global install yarn && \
  apt-get purge --auto-remove -y curl gnupg && \
  rm -rf /var/lib/apt/lists/* && \
  npm install --global lighthouse && \
  mkdir -p /home/chrome/reports && chown -R chrome:chrome /home/chrome

FROM python:3.9-alpine AS base

COPY --from=FEMTOPIXEL /chrome-linux /chrome-linux

# some place we can mount and view lighthouse reports
VOLUME /home/chrome/reports
WORKDIR /home/chrome/reports
RUN apk add g++ python3-dev libxml2 libxml2-dev libffi-dev openssl-dev
RUN apk add libxslt-dev


CMD sh

# COPY requirements.txt requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt
# RUN apk del .build-deps
#
# # Run Chrome non-privileged
# USER chrome
#
# ENV CHROME_FLAGS="--headless --disable-gpu --no-sandbox"
#
# VOLUME /home/chrome/reports
#
#
# COPY / .
#
# CMD python api.py
#