version: '3.4'

services:
  lighthouse:
    image: oeh-search-meta_lighthouse:latest
    ports:
      - "5058:5058"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5058/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

